"""Regenerate the status index in README.md from the plan and survey headers.

Every plan of record (``plans/<task>/plan.md``), survey (``surveys/<topic>/survey.md``),
and reference document (``reference/*.md``) starts with a four-line header:

    Status: ACTIVE
    Updated: 2026-09-18
    Code: mbirtorch prerelease d90fd69 holds ...
    Next step: one sentence

This script reads those headers and rewrites the tables between the two marker
comments in README.md.  Run it from anywhere, with no arguments:

    python tools/status_index.py

It prints the documents whose header is missing a field or whose Updated date is
older than STALE_DAYS, so that the index also serves as a reminder.
"""
import datetime
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / 'README.md'
START = '<!-- status-index:start -->'
END = '<!-- status-index:end -->'
STALE_DAYS = 30
STATUS_ORDER = ['ACTIVE', 'PAUSED', 'APPROVED', 'PROPOSED', 'COMPLETE', 'SUPERSEDED']
FIELDS = ['Status', 'Updated', 'Code', 'Next step']
# (table title, folder, file pattern)
KINDS = [('Plans', 'plans', '*/plan.md'), ('Surveys', 'surveys', '*/survey.md'),
         ('Reference documents', 'reference', '*.md')]


def read_header(path):
    """The header fields of one document, read from its first 40 lines."""
    fields = {}
    with open(path, encoding='utf-8') as f:
        for _ in range(40):
            line = f.readline()
            if not line:
                break
            m = re.match(r'^(Status|Updated|Code|Next step):\s*(.+?)\s*$', line)
            if m and m.group(1) not in fields:
                fields[m.group(1)] = m.group(2)
    return fields


def status_key(fields):
    status = fields.get('Status', '').split()[0] if fields.get('Status') else ''
    return STATUS_ORDER.index(status) if status in STATUS_ORDER else len(STATUS_ORDER)


def stale(updated, today):
    try:
        date = datetime.date.fromisoformat(updated[:10])
    except ValueError:
        return True
    return (today - date).days > STALE_DAYS


def build_tables(today):
    lines, warnings = [], []
    for title, folder, pattern in KINDS:
        rows = []
        for path in sorted((ROOT / folder).glob(pattern)):
            fields = read_header(path)
            missing = [k for k in FIELDS if k not in fields]
            if missing:
                warnings.append(f'{path.relative_to(ROOT)}: header lacks {", ".join(missing)}')
            rel = path.relative_to(ROOT).as_posix()
            name = path.parent.name if path.name in ('plan.md', 'survey.md') else path.stem
            updated = fields.get('Updated', 'missing')
            if stale(updated, today):
                updated += ' (stale)'
                warnings.append(f'{rel}: Updated is older than {STALE_DAYS} days')
            rows.append((status_key(fields), name, rel, fields.get('Status', 'missing'), updated,
                         fields.get('Next step', 'missing')))
        lines += [f'### {title}', '', '| Item | Status | Updated | Next step |', '|---|---|---|---|']
        for _, name, rel, status, updated, nxt in sorted(rows):
            lines.append(f'| [{name}]({rel}) | {status} | {updated} | {nxt} |')
        lines.append('')
    archived = sorted(p.name for p in (ROOT / 'archive').iterdir() if p.is_dir())
    lines += ['### Archive', '', 'Closed programs, kept as records: ' +
              ', '.join(f'[{a}](archive/{a}/)' for a in archived) + '.',
              'See [archive/README.md](archive/README.md) for what each one was.', '']
    return '\n'.join(lines), warnings


def main():
    today = datetime.date.today()
    tables, warnings = build_tables(today)
    text = README.read_text(encoding='utf-8')
    start, end = text.index(START), text.index(END)
    generated = (f'{START}\n<!-- Generated by tools/status_index.py on {today.isoformat()}; '
                 f'edit the headers, not this table. -->\n\n{tables}')
    README.write_text(text[:start] + generated + text[end:], encoding='utf-8')
    print(f'README.md index regenerated ({today.isoformat()}).')
    for w in warnings:
        print('warning:', w)


if __name__ == '__main__':
    main()
